# example netlify.toml
[Settings]
  ID = "eafc52a1-2d3d-4886-b731-889be03c7f55"
[build]
  command = "hugo"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.101.0"